# Generated by Django 2.2.26 on 2022-03-06 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_angelo', '0003_auto_20220306_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycle_angelo.UserProfile'),
        ),
    ]
