# Generated by Django 2.2.26 on 2022-03-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_angelo', '0004_auto_20220306_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
