# Generated by Django 2.2.26 on 2022-03-04 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_angelo', '0005_auto_20220303_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_ID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('likes', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, upload_to='blog_post_images')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycle_angelo.Post'),
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
